apiVersion: v1
kind: Service
metadata:
  name: message-board-service
spec:
  selector:
    app: message-board
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001
  