apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  checksum/config: {{ .Files.Get "values.yaml" | sha256sum }}
data:
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote}}
{{- end }}
