apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  {{- range $port := .Values.service.ports}}
  - port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    nodePort: {{ $port.nodePort }}
  {{- end }}
  type: {{ .Values.service.type }}