apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  {{- with .Values.persistentvolumeclaim.spec }}
  accessModes:
    {{- with .accessModes }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  resources:
    requests:
      storage: {{ .resources.requests.storage }}
  {{- end }}