apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
spec:
  {{- with .Values.persistentvolume.spec }}
  capacity:
    storage: {{ .capacity.storage }}
  accessModes:
    {{- with .accessModes }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  hostPath:
    path: {{ .hostPath.path }}
  {{- end }}