apiVersion: batch/v1
kind: CronJob
metadata:
  name: time-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: time-cronjob
            image: distroit/schedule_app
            imagePullPolicy: Always
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1  